'use strict';
function levelPlan(entries){return entries.map(function(entry){return [entry[0],entry[1]];});}
var BUILD_LIBRARY=[
  {id:'monk-open-hand-thief',name:'散打宗 · 连击武僧',classId:'monk',subclass:'散打宗',split:'散打宗武僧 9 / 盗贼 3',tier:'强力',difficulty:'中等',version:'Patch 8 + Hotfix',checkedAt:'2026-09-19',sources:['https://bg3.wiki/wiki/Way_of_the_Open_Hand','https://bg3.wiki/wiki/Tavern_Brawler'],levels:levelPlan([['武僧 1','徒手攻击与气资源。'],['武僧 2','疾风连击与机动。'],['武僧 3','选择散打宗。'],['武僧 4','酒馆殴斗者。'],['武僧 5','额外攻击与震慑拳。'],['武僧 6','散打宗附伤。'],['武僧 7','防御提升。'],['武僧 8','补属性或警觉。'],['武僧 9','完成武僧主体。'],['盗贼 1','技能专精。'],['盗贼 2','灵巧动作。'],['盗贼 3','盗贼额外附赠动作。']]),rotation:['接近高威胁目标。','疾风连击制造倒地或震慑。','短休恢复气资源。'],gearPlan:{core:['cloth','boots'],strong:[],replacements:[{for:'cloth',alternatives:['robe'],reason:'需要更高防御时替换。'}]},risks:['属性点需要在力量、敏捷、体质和感知间取舍。','荣誉模式和装备来源可能改变最佳加点。']},
  {id:'barbarian-giant-throw',name:'巨人之道 · 巨人投掷',classId:'barbarian',subclass:'巨人之道',split:'巨人之道野蛮人 6 / 战士 2 / 盗贼 4',tier:'强力',difficulty:'中等',version:'Patch 8 + Hotfix',checkedAt:'2026-09-19',sources:['https://bg3.wiki/wiki/Path_of_the_Giant','https://baldursgate3.game/news/the-final-patch-new-subclasses-photo-mode-and-cross-play_138'],levels:levelPlan([['野蛮人 1','力量投掷与近战过渡。'],['野蛮人 2','鲁莽攻击只在能承受被命中时开启。'],['野蛮人 3','选择巨人之道。'],['野蛮人 4','酒馆殴斗者，优先力量。'],['野蛮人 5','额外攻击与快速移动。'],['野蛮人 6','取得巨人投掷强化。'],['战士 1','防御战斗风格。'],['战士 2','动作如潮。'],['盗贼 1','技能专精；投掷不触发偷袭。'],['盗贼 2','灵巧动作找投掷视线。'],['盗贼 3','盗贼的额外附赠动作。'],['盗贼 4','力量或警觉。']]),rotation:['确认投掷轨迹与落点后进入狂暴。','用附赠动作投掷优先处理施法者。','动作如潮只留给能结束战斗或救场的回合。'],gearPlan:{core:['pike','flinging'],strong:['gloves','cloth'],replacements:[{for:'cloth',alternatives:['luminous'],reason:'仅在需要中甲防御时的临时替代，不增加投掷伤害。'}]},risks:['投掷轨迹会被横梁、门框和高低差阻挡。','当前图鉴没有终盘投掷武器；优雅布衣和发光护甲只是防御临时件。','狂暴期间不能施法或维持专注。']},
  {id:'barbarian-berserker-throw',name:'狂战士之道 · 狂战投掷',classId:'barbarian',subclass:'狂战士之道',split:'狂战士之道野蛮人 5 / 盗贼 4 / 战士 3',tier:'强力',difficulty:'容易',version:'Patch 8 + Hotfix',checkedAt:'2026-09-19',sources:['https://bg3.wiki/wiki/Path_of_the_Berserker','https://bg3.wiki/wiki/Enraged_Throw'],levels:levelPlan([['野蛮人 1','力量与投掷武器起步。'],['野蛮人 2','鲁莽攻击不是无代价命中。'],['野蛮人 3','选择狂战士之道与狂乱。'],['野蛮人 4','酒馆殴斗者，优先力量。'],['野蛮人 5','额外攻击。'],['盗贼 1','技能专精。'],['盗贼 2','灵巧动作。'],['盗贼 3','盗贼额外附赠动作。'],['盗贼 4','力量或警觉。'],['战士 1','防御战斗风格。'],['战士 2','动作如潮。'],['战士 3','战斗大师的精准攻击。']]),rotation:['进入狂乱后用狂乱投掷压制高威胁目标。','以额外附赠动作维持投掷节奏。','高护甲目标先用精准攻击或优势条件。'],gearPlan:{core:['pike','flinging'],strong:['gloves','cloth'],replacements:[{for:'cloth',alternatives:['luminous'],reason:'只是无甲防御不够时的中甲临时替代，不是投掷毕业件。'}]},risks:['狂乱投掷和巨人之道的元素投掷是不同机制。','现有图鉴没有终盘投掷替代武器。','狂暴限制施法和专注。']},
  {id:'barbarian-wildheart-melee',name:'荒蛮之心之道 · 重武器前排',classId:'barbarian',subclass:'荒蛮之心之道',split:'荒蛮之心之道野蛮人 12',tier:'稳健',difficulty:'容易',version:'Patch 8 + Hotfix',checkedAt:'2026-09-19',sources:['https://bg3.wiki/wiki/Path_of_the_Wildheart','https://bg3.wiki/wiki/Great_Weapon_Master:_All_In'],levels:levelPlan([['野蛮人 1','狂暴与无甲防御。'],['野蛮人 2','鲁莽攻击换取优势。'],['野蛮人 3','选择荒蛮之心与兽性之心。'],['野蛮人 4','力量+2。'],['野蛮人 5','额外攻击。'],['野蛮人 6','选择兽性面向。'],['野蛮人 7','先攻相关能力提升。'],['野蛮人 8','巨武器大师；命中低时关闭全力一击。'],['野蛮人 9','残暴重击。'],['野蛮人 10','补充荒蛮之心能力。'],['野蛮人 11','顽强狂暴。'],['野蛮人 12','力量、警觉或幸运。']]),rotation:['狂暴后贴住高威胁目标。','有优势或高命中时开启巨武器大师。','兽性能力按保护、追击或承伤需要使用。'],gearPlan:{core:['cloth'],strong:['luminous'],replacements:[{for:'cloth',alternatives:['luminous'],reason:'仅在无甲防御落后时用作中甲临时替代；现有图鉴没有重武器专属核心件。'}]},risks:['这是稳健纯职前排，不宣称为投掷流最高单体输出。','鲁莽攻击会提高敌人的命中。','现有图鉴的衣甲只是临时防御方案。']},
  {id:'bard-swords-archer-control',name:'剑刃学院 · 远程控场',classId:'bard',subclass:'剑刃学院',split:'剑刃学院吟游诗人 10 / 战士 2',tier:'强力',difficulty:'中等',version:'Patch 8 + Hotfix',checkedAt:'2026-09-19',sources:['https://bg3.wiki/wiki/College_of_Swords','https://bg3.wiki/wiki/Band_of_the_Mystic_Scoundrel'],levels:levelPlan([['吟游诗人 1','治愈真言、妖火术与对话技能。'],['吟游诗人 2','休憩曲增加队伍短休。'],['吟游诗人 3','选择剑刃学院；远程华舞可用，但学院不提供箭术战斗风格。'],['吟游诗人 4','敏捷+2。'],['吟游诗人 5','激励短休恢复，准备控制法术。'],['吟游诗人 6','额外攻击与剑刃华舞。'],['吟游诗人 7','四环控制法术。'],['吟游诗人 8','敏捷+2或神射手。'],['吟游诗人 9','补足高环控制。'],['吟游诗人 10','魔法奥秘填补队伍缺口。'],['战士 1','此时取得箭术战斗风格。'],['战士 2','动作如潮。']]),rotation:['先以远程华舞命中，再利用法术控制敌群。','有神秘恶棍之戒时，命中后可用附赠动作施放惑控或幻术。','优先射杀未被控制的高威胁目标。'],gearPlan:{core:['cloth'],strong:['robe'],replacements:[{for:'cloth',alternatives:['robe'],reason:'偏向魅力戏法与控制时的临时选择，会失去敏捷、先攻和武器命中。'}]},risks:['剑刃学院在3级不提供箭术战斗风格；本路线到角色11级战士1才取得。','当前图鉴未收录远程控场毕业装备。','神射手面对高护甲敌人应关闭。']},
  {id:'bard-swords-melee',name:'剑刃学院 · 双持近战',classId:'bard',subclass:'剑刃学院',split:'剑刃学院吟游诗人 10 / 战士 2',tier:'稳健',difficulty:'中等',version:'Patch 8 + Hotfix',checkedAt:'2026-09-19',sources:['https://bg3.wiki/wiki/College_of_Swords','https://bg3.wiki/wiki/Defensive_Flourish'],levels:levelPlan([['吟游诗人 1','灵巧武器与治愈真言起步。'],['吟游诗人 2','休憩曲。'],['吟游诗人 3','剑刃学院与双武器战斗风格。'],['吟游诗人 4','敏捷+2。'],['吟游诗人 5','激励短休恢复。'],['吟游诗人 6','额外攻击与防御华舞。'],['吟游诗人 7','四环机动或控制法术。'],['吟游诗人 8','敏捷+2或警觉。'],['吟游诗人 9','五环法术。'],['吟游诗人 10','魔法奥秘。'],['战士 1','防御战斗风格。'],['战士 2','动作如潮。']]),rotation:['以防御华舞进入危险区域。','用武器输出与控制法术交替处理目标。','附赠动作在副手攻击和控制间取舍。'],gearPlan:{core:['cloth'],strong:['luminous'],replacements:[{for:'cloth',alternatives:['luminous'],reason:'中甲熟练可用的临时防御替代；不提供双持伤害机制。'}]},risks:['近战剑刃诗人不是纯前排坦克。','当前图鉴没有双持专属核心件。','附赠动作会在副手攻击和法术之间竞争。']},
  {id:'bard-glamour-support',name:'魅惑学院 · 队伍辅助',classId:'bard',subclass:'魅惑学院',split:'魅惑学院吟游诗人 12',tier:'稳健',difficulty:'容易',version:'Patch 8 + Hotfix',checkedAt:'2026-09-19',sources:['https://bg3.wiki/wiki/College_of_Glamour','https://baldursgate3.game/news/the-final-patch-new-subclasses-photo-mode-and-cross-play_138'],levels:levelPlan([['吟游诗人 1','治愈真言、妖火术和不谐低语。'],['吟游诗人 2','休憩曲。'],['吟游诗人 3','选择魅惑学院，鼓舞队友换位。'],['吟游诗人 4','魅力+2。'],['吟游诗人 5','激励短休恢复。'],['吟游诗人 6','魅惑学院中段辅助能力。'],['吟游诗人 7','四环控制或防护。'],['吟游诗人 8','魅力+2。'],['吟游诗人 9','五环法术。'],['吟游诗人 10','魔法奥秘。'],['吟游诗人 11','六环法术。'],['吟游诗人 12','警觉、幸运或战地施法者。']]),rotation:['给需要换位的队友临时生命和移动。','优先控制会打乱阵型的敌人。','保留治愈真言救起倒地队友。'],gearPlan:{core:['robe'],strong:['cloth'],replacements:[{for:'robe',alternatives:['cloth'],reason:'更需要敏捷和先攻时的临时替代，会降低魅力戏法收益。'}]},risks:['魅惑学院的价值是队伍节奏，不是纯输出最高。','临时生命不与其他临时生命叠加。','当前图鉴没有魅惑学院专属辅助装备。']},
  {id:'cleric-light-orb',name:'光明领域 · 光耀法球',classId:'cleric',subclass:'光明领域',split:'光明牧师 12',tier:'强力',difficulty:'容易',version:'Patch 8 + Hotfix',checkedAt:'2026-09-19',sources:['https://bg3.wiki/wiki/Light_Domain','https://bg3.wiki/wiki/Luminous_Armour'],levels:levelPlan([['牧师 1','光明领域、祝福术与治愈真言。'],['牧师 2','领域引导神力。'],['牧师 3','灵体武器。'],['牧师 4','感知+2。'],['牧师 5','灵体卫士与领域火球术。'],['牧师 6','保护队友的领域能力。'],['牧师 7','四环法术。'],['牧师 8','感知+2。'],['牧师 9','五环法术。'],['牧师 10','谨慎使用神圣干预。'],['牧师 11','六环法术。'],['牧师 12','警觉或战地施法者。']]),rotation:['灵体卫士移动覆盖敌人，触发光耀法球。','敌群集中时用领域能力或火球术。','面对光耀反击时改用控制或治疗。'],gearPlan:{core:['luminous'],strong:['cloth'],replacements:[{for:'luminous',alternatives:['cloth'],reason:'没拿到发光护甲时的敏捷与先攻临时替代，失去光耀法球机制。'}]},risks:['发光护甲需要中甲熟练。','灵体卫士需要专注。','光耀反击敌人需要先检查特性。']},
  {id:'cleric-tempest-wet',name:'风暴领域 · 水电爆发',classId:'cleric',subclass:'风暴领域',split:'风暴牧师 12',tier:'强力',difficulty:'中等',version:'Patch 8 + Hotfix',checkedAt:'2026-09-19',sources:['https://bg3.wiki/wiki/Tempest_Domain','https://bg3.wiki/wiki/Wet_(Condition)'],levels:levelPlan([['牧师 1','风暴领域、造水术与治愈真言。'],['牧师 2','引导神力用于关键伤害。'],['牧师 3','灵体武器与二环辅助。'],['牧师 4','感知+2。'],['牧师 5','灵体卫士与召雷术。'],['牧师 6','风暴领域能力提升。'],['牧师 7','四环法术。'],['牧师 8','感知+2。'],['牧师 9','五环法术。'],['牧师 10','保留神圣干预。'],['牧师 11','六环法术。'],['牧师 12','警觉或战地施法者。']]),rotation:['先造水或投水瓶，使合适目标潮湿。','对潮湿目标用闪电伤害与引导神力。','近距离清杂可开灵体卫士。'],gearPlan:{core:['luminous'],strong:['cloth'],replacements:[{for:'luminous',alternatives:['cloth'],reason:'没有中甲时的临时敏捷方案；不增强水电伤害。'}]},risks:['召雷术、灵体卫士和急速术都需要专注。','潮湿强化闪电与寒冷，不强化雷鸣。','当前图鉴没有风暴水电专属装备。']},
  {id:'cleric-life-support',name:'生命领域 · 治疗增益',classId:'cleric',subclass:'生命领域',split:'生命牧师 12',tier:'稳健',difficulty:'容易',version:'Patch 8 + Hotfix',checkedAt:'2026-09-19',sources:['https://bg3.wiki/wiki/Life_Domain','https://bg3.wiki/wiki/Mass_Healing_Word'],levels:levelPlan([['牧师 1','生命领域、祝福术与治愈真言。'],['牧师 2','领域引导神力救场。'],['牧师 3','灵体武器与群体辅助。'],['牧师 4','感知+2。'],['牧师 5','灵体卫士与群体治疗真言。'],['牧师 6','领域治疗能力提升。'],['牧师 7','四环防护。'],['牧师 8','感知+2。'],['牧师 9','五环群体恢复。'],['牧师 10','神圣干预留给关键节点。'],['牧师 11','六环法术。'],['牧师 12','警觉或战地施法者。']]),rotation:['战前用低成本增益。','优先救起倒地队友，再处理过量治疗。','空闲回合用控制或灵体卫士贡献。'],gearPlan:{core:['luminous'],strong:['cloth'],replacements:[{for:'luminous',alternatives:['cloth'],reason:'图鉴尚无生命领域治疗件；这是临时防御替代，不代表治疗核心。'}]},risks:['生命领域强在容错，不是每回合抬满全队。','治疗和增益消耗法术位。','关键保命法术可能需要专注。']},
  {id:'druid-stars-caster',name:'星辰结社 · 远程施法',classId:'druid',subclass:'星辰结社',split:'星辰德鲁伊 12',tier:'强力',difficulty:'中等',version:'Patch 8 + Hotfix',checkedAt:'2026-09-19',sources:['https://bg3.wiki/wiki/Circle_of_the_Stars','https://baldursgate3.game/news/the-final-patch-new-subclasses-photo-mode-and-cross-play_138'],levels:levelPlan([['德鲁伊 1','纠缠术、治愈真言与造水术。'],['德鲁伊 2','星辰结社与三种星辰形态。'],['德鲁伊 3','月华之光和荆棘丛生。'],['德鲁伊 4','感知+2。'],['德鲁伊 5','三环法术。'],['德鲁伊 6','星辰结社能力提升。'],['德鲁伊 7','四环法术。'],['德鲁伊 8','感知+2。'],['德鲁伊 9','五环法术。'],['德鲁伊 10','星辰形态进一步成长。'],['德鲁伊 11','六环法术。'],['德鲁伊 12','警觉或战地施法者。']]),rotation:['输出选弓手、治疗选圣杯、保专注选巨龙。','先铺控制或召唤，再用星辰攻击补伤害。','按战场职责分配有限变形次数。'],gearPlan:{core:['cloth'],strong:['luminous'],replacements:[{for:'cloth',alternatives:['luminous'],reason:'需要中甲防御时的临时替代，不增强星辰形态。'}]},risks:['巨龙形态不保证专注永不失败。','装备应让给更依赖的队友时可用临时衣甲。','控制地形和召唤物会堵路。']},
  {id:'druid-moon-wildshape',name:'月亮结社 · 野性变形前排',classId:'druid',subclass:'月亮结社',split:'月亮德鲁伊 12',tier:'稳健',difficulty:'中等',version:'Patch 8 + Hotfix',checkedAt:'2026-09-19',sources:['https://bg3.wiki/wiki/Circle_of_the_Moon','https://bg3.wiki/wiki/Wild_Shape'],levels:levelPlan([['德鲁伊 1','治愈真言与纠缠术。'],['德鲁伊 2','月亮结社与战斗野性变形。'],['德鲁伊 3','二环法术和高等级形态。'],['德鲁伊 4','感知+2或警觉。'],['德鲁伊 5','三环法术与新形态。'],['德鲁伊 6','月亮结社强化。'],['德鲁伊 7','四环法术。'],['德鲁伊 8','感知+2。'],['德鲁伊 9','五环法术。'],['德鲁伊 10','高阶月亮形态。'],['德鲁伊 11','六环法术。'],['德鲁伊 12','警觉、战地施法者或属性提升。']]),rotation:['先施放准备法术，再变形进前线。','用形态封锁通路并保护脆弱队友。','形态生命不足或需要施法时主动解除。'],gearPlan:{core:['cloth'],strong:['luminous'],replacements:[{for:'cloth',alternatives:['luminous'],reason:'仅是变形前人形的临时防御替代；变形期间装备效果需以游戏实际生效为准。'}]},risks:['野性变形会改变可用动作和法术。','装备效果不会都按人形方式工作。','这是承伤控场，不承诺最高单体伤害。']},
  {id:'druid-land-control',name:'大地结社 · 地形控制召唤',classId:'druid',subclass:'大地结社',split:'大地德鲁伊 12',tier:'稳健',difficulty:'中等',version:'Patch 8 + Hotfix',checkedAt:'2026-09-19',sources:['https://bg3.wiki/wiki/Circle_of_the_Land','https://bg3.wiki/wiki/Conjure_Woodland_Being'],levels:levelPlan([['德鲁伊 1','纠缠术、治愈真言与造水术。'],['德鲁伊 2','选择大地结社并取得自然恢复。'],['德鲁伊 3','二环地形法术。'],['德鲁伊 4','感知+2。'],['德鲁伊 5','三环控制范围提升。'],['德鲁伊 6','取得大地步伐，穿越困难地形更稳。'],['德鲁伊 7','四环召唤或控制。'],['德鲁伊 8','感知+2。'],['德鲁伊 9','五环战场改造。'],['德鲁伊 10','补足结社赠予法术。'],['德鲁伊 11','六环召唤或控制。'],['德鲁伊 12','警觉或战地施法者。']]),rotation:['先以地形法术切割敌人。','召唤物用于占位，但要给队友留路。','短休后以自然恢复回收法术位，再规划下一场控制。'],gearPlan:{core:['cloth'],strong:['luminous'],replacements:[{for:'cloth',alternatives:['luminous'],reason:'中甲防御的临时替代，不取代地形控制和专注管理。'}]},risks:['自然恢复在2级取得，不是6级能力。','很多控制与召唤需要专注。','地面控制会影响友军移动和视线。']}
];
var PATCH8_SOURCE='https://baldursgate3.game/news/the-final-patch-new-subclasses-photo-mode-and-cross-play_138';
function martialBuild(build){
  build.version='Patch 8 + Hotfix';
  build.checkedAt='2026-09-19';
  build.sources=[PATCH8_SOURCE,build.wiki];
  delete build.wiki;
  build.levels=levelPlan(build.levels);
  return build;
}
BUILD_LIBRARY.push(
  martialBuild({id:'fighter-battlemaster-gwm',name:'战斗大师 · 重武器压制',classId:'fighter',subclass:'战斗大师',split:'战斗大师战士 12',tier:'强力',difficulty:'中等',wiki:'https://bg3.wiki/wiki/Battle_Master',levels:[['战士 1','选防御或巨武器战斗风格。'],['战士 2','动作如潮留给关键回合。'],['战士 3','战斗大师；精准、绊摔与缴械攻击。'],['战士 4','巨武器大师；命中不足时关闭全力一击。'],['战士 5','额外攻击。'],['战士 6','力量+2。'],['战士 7','补战技与战技骰。'],['战士 8','警觉或力量+2。'],['战士 9','不屈意志。'],['战士 10','补战技，按队伍控制缺口选择。'],['战士 11','第三次攻击。'],['战士 12','力量、幸运或战地施法者。']],rotation:['高护甲目标先用精准攻击或制造优势。','绊摔、缴械优先交给能改变战局的敌人。','动作如潮只在能击杀关键目标或救场时开启。'],gearPlan:{core:['giantslayer'],strong:['adamantine'],replacements:[{for:'giantslayer',alternatives:['phalar'],reason:'未取得终盘巨剑前可双手使用作为团队增益过渡，伤害定位不同。'}]},risks:['巨武器大师的命中惩罚在高护甲敌人面前很明显。','荣誉模式的加速动作不提供旧版额外攻击叠加；不要把它当作无限爆发。']}),
  martialBuild({id:'fighter-battlemaster-archer',name:'战斗大师 · 战技弓手',classId:'fighter',subclass:'战斗大师',split:'战斗大师战士 12',tier:'强力',difficulty:'容易',wiki:'https://bg3.wiki/wiki/Battle_Master',levels:[['战士 1','选箭术战斗风格。'],['战士 2','动作如潮。'],['战士 3','战斗大师；精准攻击优先。'],['战士 4','神射手；高护甲目标可关闭。'],['战士 5','额外攻击。'],['战士 6','敏捷+2。'],['战士 7','补推击或恐吓攻击。'],['战士 8','敏捷+2或警觉。'],['战士 9','不屈意志。'],['战士 10','补战技骰与战技。'],['战士 11','第三次攻击。'],['战士 12','敏捷、幸运或警觉。']],rotation:['先从高处或优势位置攻击。','神射手命中不足时先用精准攻击，再考虑关闭被动。','推击用于打断站位而非随便消耗战技骰。'],gearPlan:{core:['gontr'],strong:['darkfire'],replacements:[{for:'gontr',alternatives:['dead-shot'],reason:'铸造厂路线未完成前可用商店弓过渡，失去贡德信赖的团队支援。'}]},risks:['神射手并非每回合都应开启。','荣誉模式加速动作不会复刻旧版完整额外攻击叠加。']}),
  martialBuild({id:'fighter-arcane-archer',name:'奥术射手 · 元素箭矢',classId:'fighter',subclass:'奥术射手',split:'奥术射手战士 12',tier:'稳健',difficulty:'中等',wiki:'https://bg3.wiki/wiki/Arcane_Archer',levels:[['战士 1','选箭术战斗风格。'],['战士 2','动作如潮。'],['战士 3','选择奥术射手；奥术箭的豁免 DC = 8 + 熟练加值 + 智力调整值，敏捷仍决定武器命中。'],['战士 4','敏捷+2；若主打需要豁免的控制箭可改选智力+2。'],['战士 5','额外攻击。'],['战士 6','敏捷+2或神射手。'],['战士 7','奥术射手能力成长。'],['战士 8','警觉或神射手。'],['战士 9','不屈意志。'],['战士 10','补奥术箭选择。'],['战士 11','第三次攻击。'],['战士 12','敏捷、幸运或警觉。']],rotation:['普通箭靠敏捷维持稳定输出；需要目标豁免的奥术箭则看智力与豁免 DC。','先确认地表、抗性和友军站位再选元素箭。','需要终结目标时再配合动作如潮。'],gearPlan:{core:['dead-shot'],strong:['darkfire'],replacements:[{for:'dead-shot',alternatives:['gontr'],reason:'若已完成铸造厂，贡德信赖是更强但队伍竞争激烈的替代。'}]},risks:['奥术射手是 Patch 8 新子职业，强项是箭矢选择而非无条件最高普攻。','元素箭可能被抗性、地形或友军位置抵消价值。']}),
  martialBuild({id:'monk-shadow-infiltrator',name:'暗影宗 · 潜袭武僧',classId:'monk',subclass:'暗影宗',split:'暗影宗武僧 8 / 盗贼 4',tier:'稳健',difficulty:'高',wiki:'https://bg3.wiki/wiki/Way_of_Shadow',levels:[['武僧 1','徒手与敏捷武器过渡。'],['武僧 2','气点与机动。'],['武僧 3','选择暗影宗，取得潜入工具。'],['武僧 4','警觉或敏捷+2。'],['武僧 5','额外攻击与震慑拳。'],['武僧 6','暗影宗机动能力。'],['武僧 7','防御提升。'],['武僧 8','敏捷+2。'],['盗贼 1','技能专精。'],['盗贼 2','灵巧动作。'],['盗贼 3','盗贼额外附赠动作。'],['盗贼 4','警觉或敏捷+2。']],rotation:['战斗前优先选暗处、高处和隔离目标。','用暗影机动接近后，以震慑或击倒打开窗口。','无安全潜入条件时按普通机动近战处理，不强求潜袭。'],gearPlan:{core:['undermountain'],strong:['night-walkers'],replacements:[{for:'undermountain',alternatives:['phalar'],reason:'未拿到短剑时可用作近战过渡，但不提供同样的暴击骰改善。'}]},risks:['需要主动规划光照、视线和队伍站位。','潜行或暗影位移不保证所有战斗都能取得受惊开场。']}),
  martialBuild({id:'monk-drunken-master',name:'醉拳宗 · 酒套扰乱',classId:'monk',subclass:'醉拳宗',split:'醉拳宗武僧 12',tier:'趣味／主题',difficulty:'高',wiki:'https://bg3.wiki/wiki/Way_of_the_Drunken_Master',levels:[['武僧 1','徒手攻击与机动起步。'],['武僧 2','气点和疾风连击。'],['武僧 3','选择醉拳宗；醉拳技巧取代疾风连击，连打两拳后获得脱离和额外移动。'],['武僧 4','Intoxicating Strike 以徒手攻击要求目标通过体质豁免，否则醉酒；命中后获得 Life of the Party。'],['武僧 5','额外攻击与震慑拳。'],['武僧 6','醉拳宗中段扰乱能力。'],['武僧 7','防御提升。'],['武僧 8','感知或敏捷+2。'],['武僧 9','气共鸣与机动。'],['武僧 10','净化与醉拳能力成长。'],['武僧 11','高阶醉拳宗能力。'],['武僧 12','警觉、幸运或属性提升。']],rotation:['先用 Intoxicating Strike 让高价值目标有机会醉酒；命中后获得 Life of the Party，再优先攻击醉酒目标。','需要脱离或加移动时用醉拳技巧（已取代普通疾风连击），不要把两者当成可同时使用的招式。','气点优先给震慑、击倒或救场，而非每回合强行连击。'],gearPlan:{core:['cloth'],strong:['night-walkers'],replacements:[{for:'cloth',alternatives:['dex-gloves'],reason:'当前图鉴没有醉酒套；敏捷手套只是属性过渡，不替代醉酒机制。'}]},risks:['Life of the Party 在醉酒目标前提高护甲和攻击；醉拳宗是趣味／主题，不与散打宗终盘输出混排。','现有图鉴未收录醉酒专属套装，装备建议仅为诚实过渡方案。']}),
  martialBuild({id:'paladin-vengeance-smite',name:'复仇之誓 · 至圣斩爆发',classId:'paladin',subclass:'复仇之誓',split:'复仇圣武士 12',tier:'强力',difficulty:'容易',wiki:'https://bg3.wiki/wiki/Oath_of_Vengeance',levels:[['圣武士 1','选择复仇之誓与重甲起步。'],['圣武士 2','至圣斩；开启反应询问。'],['圣武士 3','取得誓言能力。'],['圣武士 4','力量+2。'],['圣武士 5','额外攻击与二环法术。'],['圣武士 6','保护灵光。'],['圣武士 7','继续纯职，准备誓言法术。'],['圣武士 8','力量+2或巨武器大师。'],['圣武士 9','三环法术。'],['圣武士 10','勇气灵光。'],['圣武士 11','强化至圣斩。'],['圣武士 12','魅力+2或警觉。']],rotation:['先普通命中，命中或重击后按威胁投入至圣斩。','把复仇能力留给首领或关键敌人。','让需要豁免保护的队友靠近灵光。'],gearPlan:{core:['giantslayer'],strong:['adamantine'],replacements:[{for:'giantslayer',alternatives:['blood-lathander'],reason:'尚未取得巨剑时可用钉头锤提供对亡灵和邪魔的实用过渡。'}]},risks:['至圣斩会快速消耗法术位，需要长休管理。','誓言相关对话和行为会造成破誓风险。']}),
  martialBuild({id:'paladin-ancients-aura',name:'远古之誓 · 队伍灵光',classId:'paladin',subclass:'远古之誓',split:'远古圣武士 12',tier:'稳健',difficulty:'容易',wiki:'https://bg3.wiki/wiki/Oath_of_the_Ancients',levels:[['圣武士 1','远古之誓与重甲起步。'],['圣武士 2','至圣斩和防御战斗风格。'],['圣武士 3','远古之誓的控制与治疗。'],['圣武士 4','魅力+2或力量+2。'],['圣武士 5','额外攻击。'],['圣武士 6','保护灵光。'],['圣武士 7','远古灵光，保护邻近队友。'],['圣武士 8','魅力+2。'],['圣武士 9','三环法术。'],['圣武士 10','勇气灵光。'],['圣武士 11','强化至圣斩。'],['圣武士 12','警觉或力量+2。']],rotation:['开战先把灵光范围覆盖易受伤队友。','治疗与控制优先服务濒危队友，再进行至圣斩补刀。','队伍分散时不要为覆盖灵光牺牲安全站位。'],gearPlan:{core:['adamantine'],strong:['night-walkers'],replacements:[{for:'adamantine',alternatives:['persistence'],reason:'若精金材料分配给别人，第三章改用同为重甲的坚韧护甲；失去精金护甲的抗暴击属性。'}]},risks:['灵光需要站位配合，不能覆盖全地图。','治疗、控制和至圣斩会竞争有限法术位。']}),
  martialBuild({id:'paladin-crown-control',name:'王冠之誓 · 前排控制',classId:'paladin',subclass:'王冠之誓',split:'王冠圣武士 12',tier:'稳健',difficulty:'中等',wiki:'https://bg3.wiki/wiki/Oath_of_the_Crown',levels:[['圣武士 1','王冠之誓与重甲起步。'],['圣武士 2','至圣斩和防御战斗风格。'],['圣武士 3','选择王冠之誓，取得控制工具。'],['圣武士 4','魅力+2。'],['圣武士 5','额外攻击。'],['圣武士 6','保护灵光。'],['圣武士 7','神圣忠诚：1.5 米内盟友受伤时用反应保护并治疗盟友 2×圣武士等级，自己承受同等固定光耀伤害。'],['圣武士 8','力量+2或警觉。'],['圣武士 9','三环控制与辅助。'],['圣武士 10','勇气灵光。'],['圣武士 11','强化至圣斩。'],['圣武士 12','魅力、幸运或战地施法者。']],rotation:['先用王冠控制把高威胁敌人留在前线。','在命中确认后才投入高环至圣斩。','控制失败时以灵光保护和重甲承伤稳住回合。'],gearPlan:{core:['adamantine'],strong:['blood-lathander'],replacements:[{for:'adamantine',alternatives:['persistence'],reason:'精金材料另有分配时，以同为重甲的坚韧护甲维持前排防护；失去精金护甲的抗暴击属性。'}]},risks:['王冠之誓是 Patch 8 新子职业；控制通常有豁免，不能当作必中。','神圣忠诚会以自身生命交换邻近盟友的保护，残血时应关闭反应。','誓言行为与队伍决定可能造成破誓。']}),
  martialBuild({id:'ranger-gloom-assassin',name:'幽暗追踪者 · 刺客伏击',classId:'ranger',subclass:'幽暗追踪者',split:'幽暗追踪游侠 5 / 刺客 4 / 战士 3',tier:'强力',difficulty:'高',wiki:'https://bg3.wiki/wiki/Gloom_Stalker',levels:[['游侠 1','选择宿敌和探索者能力。'],['游侠 2','箭术战斗风格与猎人印记。'],['游侠 3','幽暗追踪者。'],['游侠 4','敏捷+2或神射手。'],['游侠 5','额外攻击。'],['游荡者 1','偷袭与技能专精。'],['游荡者 2','灵巧动作。'],['游荡者 3','刺客，理解受惊条件。'],['游荡者 4','敏捷+2或神射手。'],['战士 1','防御战斗风格。'],['战士 2','动作如潮。'],['战士 3','战斗大师精准攻击。']],rotation:['脱离敌人视野后从高处或潜行开战。','首轮集中高威胁目标，受惊不成立时改用稳定输出。','动作如潮只在首轮能够决定战局时使用。'],gearPlan:{core:['gontr'],strong:['risky-ring'],replacements:[{for:'gontr',alternatives:['dead-shot'],reason:'铸造厂前可用商店弓，失去贡德信赖的保护和命中支援。'}]},risks:['对话开战和部分敌人无法制造受惊，不能保证首轮暴击。','风险之戒会让豁免劣势，遇到控制敌人应考虑换下。']}),
  martialBuild({id:'ranger-hunter-volley',name:'猎人 · 多目标齐射',classId:'ranger',subclass:'猎人',split:'猎人游侠 12',tier:'稳健',difficulty:'中等',wiki:'https://bg3.wiki/wiki/Hunter',levels:[['游侠 1','选择探索者与宿敌能力。'],['游侠 2','箭术战斗风格。'],['游侠 3','猎人子职业，选适合队伍的猎物能力。'],['游侠 4','敏捷+2。'],['游侠 5','额外攻击。'],['游侠 6','补探索者能力。'],['游侠 7','猎人防御能力。'],['游侠 8','敏捷+2或神射手。'],['游侠 9','三环游侠法术。'],['游侠 10','自然探索能力。'],['游侠 11','齐射，处理密集敌群。'],['游侠 12','警觉或幸运。']],rotation:['敌群聚拢时用齐射，分散时回到单体普攻。','优先找不会伤及队友的射线和落点。','猎人印记与多目标回合的附赠动作要取舍。'],gearPlan:{core:['gontr'],strong:['darkfire'],replacements:[{for:'gontr',alternatives:['dead-shot'],reason:'未完成铸造厂前用商店弓过渡，齐射机制不受影响。'}]},risks:['齐射需要敌人位置配合，不能为了多打一个目标误伤队友。','神射手在高护甲目标前需按命中率关闭。']}),
  martialBuild({id:'ranger-swarmkeeper-control',name:'虫群守卫 · 位移控制',classId:'ranger',subclass:'虫群守卫',split:'虫群守卫游侠 12',tier:'稳健',difficulty:'中等',wiki:'https://bg3.wiki/wiki/Swarmkeeper',levels:[['游侠 1','选择探索者和宿敌能力。'],['游侠 2','箭术或双武器战斗风格。'],['游侠 3','虫群守卫：命中后每回合一次，蜜蜂可击退，三种虫群均可把自己传送；水母可施加 Shock、飞蛾可致盲，不存在把敌人向自己拖拽的选项。'],['游侠 4','感知+2或敏捷+2。'],['游侠 5','额外攻击。'],['游侠 6','补探索者能力。'],['游侠 7','虫群守卫机动强化。'],['游侠 8','感知或敏捷+2。'],['游侠 9','三环控制法术。'],['游侠 10','自然探索能力。'],['游侠 11','高阶虫群控制。'],['游侠 12','警觉或幸运。']],rotation:['按蜂群击退、水母 Shock 或飞蛾致盲的实际类型选效果；传送只移动自己，不移动敌人。','对悬崖、地表和友军误伤先检查方向。','控制已足够时以普通攻击节省资源。'],gearPlan:{core:['darkfire'],strong:['risky-ring'],replacements:[{for:'darkfire',alternatives:['dead-shot'],reason:'不需要急速术时可换成终盘弓，失去抗性与施法辅助。'}]},risks:['虫群守卫是 Patch 8 新子职业；蜜蜂才有击退，水母与飞蛾分别施加 Shock 和致盲。','风险之戒对需要豁免的控制型游侠代价更高。']}),
  martialBuild({id:'rogue-thief-dual-wield',name:'盗贼 · 双持游击',classId:'rogue',subclass:'盗贼',split:'盗贼游荡者 12',tier:'稳健',difficulty:'容易',wiki:'https://bg3.wiki/wiki/Thief',levels:[['游荡者 1','技能专精与偷袭。'],['游荡者 2','灵巧动作。'],['游荡者 3','盗贼，取得额外附赠动作。'],['游荡者 4','敏捷+2。'],['游荡者 5','提升承伤能力。'],['游荡者 6','补技能专精。'],['游荡者 7','提升范围伤害防御。'],['游荡者 8','敏捷+2。'],['游荡者 9','盗贼能力成长。'],['游荡者 10','警觉或幸运。'],['游荡者 11','可靠才能。'],['游荡者 12','双持者或属性提升。']],rotation:['先满足偷袭条件；副手攻击每次消耗一个附赠动作，额外附赠动作才可支持第二次副手攻击或脱离。','额外附赠动作优先服务走位和生存。','不要把每个附赠动作都当成输出，危险时先躲藏或撤离。'],gearPlan:{core:['undermountain'],strong:['risky-ring'],replacements:[{for:'undermountain',alternatives:['phalar'],reason:'还未到养育间时可用作为双手近战过渡，暴击收益不同。'}]},risks:['纯盗贼没有战士式额外攻击。','偷袭需要武器和战场条件，不能把每次攻击都计入。']}),
  martialBuild({id:'rogue-assassin-ambush',name:'刺客 · 受惊伏击',classId:'rogue',subclass:'刺客',split:'刺客游荡者 12',tier:'稳健',difficulty:'高',wiki:'https://bg3.wiki/wiki/Assassin',levels:[['游荡者 1','技能专精与偷袭。'],['游荡者 2','灵巧动作。'],['游荡者 3','刺客，理解受惊开场。'],['游荡者 4','敏捷+2。'],['游荡者 5','提升承伤能力。'],['游荡者 6','补技能专精。'],['游荡者 7','提升范围伤害防御。'],['游荡者 8','警觉或敏捷+2。'],['游荡者 9','刺客能力成长。'],['游荡者 10','警觉或幸运。'],['游荡者 11','可靠才能。'],['游荡者 12','敏捷或双持者。']],rotation:['开战前断开队伍、确认视线并从潜行首击。','受惊未触发时不要冒险留在敌群，改打偷袭和撤离。','高威胁目标优先于面板低血量目标。'],gearPlan:{core:['dead-shot'],strong:['risky-ring'],replacements:[{for:'dead-shot',alternatives:['undermountain'],reason:'近距离或尚未购买终盘弓时可用短剑维持暴击收益，攻击方式不同。'}]},risks:['受惊依赖开战方式和敌人状态；对话触发的战斗常常不成立。','风险之戒的豁免劣势会放大先手失败后的风险。']}),
  martialBuild({id:'rogue-swashbuckler-duelist',name:'剑舞者 · 单挑游荡者',classId:'rogue',subclass:'剑舞者',split:'剑舞者游荡者 12',tier:'趣味／主题',difficulty:'中等',wiki:'https://bg3.wiki/wiki/Swashbuckler',levels:[['游荡者 1','技能专精与灵巧武器偷袭。'],['游荡者 2','灵巧动作。'],['游荡者 3','选择剑舞者，围绕单挑和先攻。'],['游荡者 4','敏捷+2。'],['游荡者 5','提升承伤能力。'],['游荡者 6','补技能专精。'],['游荡者 7','提升范围伤害防御。'],['游荡者 8','敏捷+2或警觉。'],['游荡者 9','剑舞者能力成长。'],['游荡者 10','幸运或警觉。'],['游荡者 11','可靠才能。'],['游荡者 12','敏捷、双持者或属性提升。']],rotation:['选择孤立的高威胁敌人单挑，确保偷袭条件。','打完偷袭后用机动离开反击范围。','敌群密集时回到队友旁制造普通偷袭条件。'],gearPlan:{core:['undermountain'],strong:['night-walkers'],replacements:[{for:'undermountain',alternatives:['phalar'],reason:'暂未取得短剑时用长剑过渡，失去短剑的暴击骰改善。'}]},risks:['剑舞者是 Patch 8 新子职业，定位为单挑主题，不应被宣传为群战最高输出。','单挑条件不稳定，仍需队友提供优势或牵制。']})
);
function casterBuild(build){
  build.version='Patch 8 + Hotfix';
  build.checkedAt='2026-09-19';
  build.sources=[PATCH8_SOURCE,build.wiki];
  delete build.wiki;
  build.levels=levelPlan(build.levels);
  return build;
}
BUILD_LIBRARY.push(
  casterBuild({id:'sorcerer-draconic-fire',name:'龙族血脉 · 火焰爆发',classId:'sorcerer',subclass:'龙族血脉',split:'龙族血脉术士 12',tier:'强力',difficulty:'中等',wiki:'https://bg3.wiki/wiki/Draconic_Bloodline',levels:[['术士 1','选择红或金龙血脉；龙族韧性提高未着甲防御并增加生命。'],['术士 2','取得魔法塑能，准备双发或增效。'],['术士 3','选择双发法术；补充灼热射线或火球术。'],['术士 4','魅力+2。'],['术士 5','三环法术，火球术用于密集敌群。'],['术士 6','龙族亲和让所选元素伤害加入魅力调整值，并可花术法点获得对应抗性。'],['术士 7','四环法术与更高术法点池。'],['术士 8','魅力+2或警觉。'],['术士 9','五环法术。'],['术士 10','补一项魔法塑能；火系范围法术注意友军。'],['术士 11','六环法术。'],['术士 12','警觉、幸运或战地施法者。']],rotation:['火焰抗性目标先改用非火戏法或队友处理。','高价值单体用双发灼热射线；敌群才用火球术。','把术法点留给决定战局的双发或增效，不要每回合耗尽。'],gearPlan:{core:['spellsparkler'],strong:['weave-robe','markoheshkir'],replacements:[{for:'spellsparkler',alternatives:['markoheshkir'],reason:'第三章取得法杖后可替换；失去前期闪电充能的多段收益。'}]},risks:['火焰抗性或免疫会显著降低主轴伤害。','火球术会误伤友军，窄地形先确认落点。','双发和增效会快速消耗术法点。']}),
  casterBuild({id:'sorcerer-storm-lightning',name:'风暴术法 · 潮湿闪电',classId:'sorcerer',subclass:'风暴术法',split:'风暴术法术士 12',tier:'强力',difficulty:'中等',wiki:'https://bg3.wiki/wiki/Storm_Sorcery',levels:[['术士 1','选择风暴术法；施放一环或更高法术后可用暴风飞行调整位置。'],['术士 2','取得魔法塑能，准备双发与快速施法。'],['术士 3','选择双发法术，并准备一二环防护或控场。'],['术士 4','魅力+2。'],['术士 5','三环法术；火球术或闪电束按敌人抗性和站位选择。'],['术士 6','取得造水／毁水术、风暴之心（闪电／雷鸣抗性及近身风暴伤害）和风暴法术。'],['术士 7','四环法术。'],['术士 8','魅力+2或警觉。'],['术士 9','五环法术。'],['术士 10','补魔法塑能，按队伍资源选增效或延长。'],['术士 11','六环法术与风暴之怒：受近战攻击命中时可用反应以闪电伤害和击退回应。'],['术士 12','警觉、幸运或战地施法者。']],rotation:['术士 6 后先用造水／毁水术或水瓶使合适目标潮湿，再以闪电束穿过敌线。','暴风飞行用于脱离近战或重新找射线，不取代行动位移。','潮湿强化闪电和寒冷，不强化雷鸣；不要把两个伤害类型混算。'],gearPlan:{core:['spellsparkler'],strong:['markoheshkir','weave-robe'],replacements:[{for:'spellsparkler',alternatives:['markoheshkir'],reason:'终盘法杖提高施法质量；早期会失去闪电充能的稳定收益。'}]},risks:['闪电束会穿过友军，施法前检查整条射线。','潮湿会让敌人和队友同样更怕闪电／寒冷。','急速术、造水后的控场与其他专注法术会互相竞争。']}),
  casterBuild({id:'sorcerer-shadow-control',name:'暗影魔法 · 黑暗控场',classId:'sorcerer',subclass:'暗影魔法',split:'暗影魔法术士 12',tier:'稳健',difficulty:'高',wiki:'https://bg3.wiki/wiki/Shadow_Magic',levels:[['术士 1','选择暗影魔法，取得黑暗视觉与濒危时的暗影自保工具。'],['术士 2','取得魔法塑能；延长或双发适合控制法术。'],['术士 3','准备黑暗术、定身术等按豁免结算的控制。'],['术士 4','魅力+2。'],['术士 5','三环控制法术；黑暗术要同时考虑队友视野。'],['术士 6','取得暗影魔法的中段能力，围绕黑暗区域创造压制窗口。'],['术士 7','四环控制或机动法术。'],['术士 8','魅力+2或警觉。'],['术士 9','五环控制法术。'],['术士 10','补魔法塑能，延长法术只用于敌方难以解除的控制。'],['术士 11','六环法术。'],['术士 12','警觉、幸运或战地施法者。']],rotation:['先确认队伍是否有黑暗视觉、魔法黑暗视野或撤出范围的计划。','用黑暗隔断远程火力，再从安全边缘施加单体控制。','控制被豁免时立刻切换到伤害或位置调整，不把术法点全押在一次尝试。'],gearPlan:{core:['spellsparkler'],strong:['weave-robe','night-walkers'],replacements:[{for:'spellsparkler',alternatives:['markoheshkir'],reason:'终盘提高法术攻击和豁免难度；不再提供早期闪电充能。'}]},risks:['黑暗会阻挡己方普通远程攻击和治疗视线。','控制效果通常允许豁免，不能当作必中。','暗影魔法是 Patch 8 新子职业；具体能力以当前版本角色页为准。']}),
  casterBuild({id:'warlock-hexblade-melee',name:'咒剑士 · 魅力近战',classId:'warlock',subclass:'咒剑士',split:'咒剑士邪术师 12',tier:'强力',difficulty:'中等',wiki:'https://bg3.wiki/wiki/Hexblade',levels:[['邪术师 1','选择咒剑士；Bind Hexed Weapon 绑定一把武器并让它以魅力攻击，另有咒剑诅咒的单体爆发窗口。'],['邪术师 2','邪术祈唤优先痛苦魔能爆与近战所需选项。'],['邪术师 3','选择契约恩赐；剑之契约（Pact of the Blade）才为后续额外攻击铺路。'],['邪术师 4','魅力+2。'],['邪术师 5','深度契约：仅剑之契约获得额外攻击，链／书之契约取得各自强化；契约法术位在短休后恢复。'],['邪术师 6','咒剑士中段能力；保留诅咒处理首领。'],['邪术师 7','四环契约法术。'],['邪术师 8','魅力+2或警觉。'],['邪术师 9','五环契约法术与更多祈唤。'],['邪术师 10','补防御或控制祈唤。'],['邪术师 11','取得六环秘法术。'],['邪术师 12','警觉、幸运或战地施法者。']],rotation:['先对首领使用咒剑诅咒，再用 Bind Hexed Weapon 绑定的武器持续攻击。','近战被包围时用位移或控制拉开，不要为多打一刀吃集火。','短休前尽量用完契约法术位，但保留一格给突发控制或自保。'],gearPlan:{core:['phalar'],strong:['weave-robe','arcane-acuity'],replacements:[{for:'phalar',alternatives:['undermountain'],reason:'需要灵巧近战过渡时可换短剑；失去团队歌唱／尖啸工具。'}]},risks:['咒剑士是 Patch 8 新子职业，近战仍会承受集火。','剑之契约与深度契约需要按等级选择，不能一开始就计算额外攻击。','契约法术位数量少，不能按长休施法者的资源方式挥霍。']}),
  casterBuild({id:'warlock-eldritch-blast',name:'邪魔宗主 · 魔能爆持续输出',classId:'warlock',subclass:'邪魔宗主',split:'邪魔宗主邪术师 12',tier:'稳健',difficulty:'容易',wiki:'https://bg3.wiki/wiki/The_Fiend',levels:[['邪术师 1','选择邪魔宗主；击杀后获得临时生命，先带魔能爆。'],['邪术师 2','邪术祈唤选择痛苦魔能爆和击退魔能爆。'],['邪术师 3','选择契约恩赐；链之契约或书之契约按队伍缺口选。'],['邪术师 4','魅力+2。'],['邪术师 5','魔能爆增加第二束，契约法术位升为三环。'],['邪术师 6','邪魔宗主能力成长，继续用击杀临时生命承受小怪战。'],['邪术师 7','四环契约法术。'],['邪术师 8','魅力+2或警觉。'],['邪术师 9','五环契约法术。'],['邪术师 10','角色等级10时魔能爆增加第三束。'],['邪术师 11','取得六环秘法术。'],['邪术师 12','警觉、幸运或战地施法者。']],rotation:['每一束魔能爆可分别选目标；优先补刀换临时生命或击退到安全地形。','击退前确认不会把敌人推离队友近战或推到危险视线外。','需要群控时用契约法术位，普通回合以戏法保留资源。'],gearPlan:{core:['spellsparkler'],strong:['weave-robe','amulet-health'],replacements:[{for:'spellsparkler',alternatives:['markoheshkir'],reason:'终盘法杖改善施法数值；会失去前期多束命中的闪电充能。'}]},risks:['击退可能破坏近战队友的站位或把敌人推到掩体。','临时生命不与其他临时生命叠加。','魔能爆束数按角色等级成长，不能提前计算。']}),
  casterBuild({id:'warlock-control-summon',name:'旧日支配者 · 控制召唤',classId:'warlock',subclass:'旧日支配者',split:'旧日支配者邪术师 12',tier:'稳健',difficulty:'中等',wiki:'https://bg3.wiki/wiki/The_Great_Old_One',levels:[['邪术师 1','选择旧日支配者，准备惑控或恐惧类法术。'],['邪术师 2','祈唤优先痛苦魔能爆；另一格按控制或视野需求选择。'],['邪术师 3','选择链之契约，取得可侦察和占位的魔宠。'],['邪术师 4','魅力+2。'],['邪术师 5','三环契约法术，准备饥饿之寒等区域控制。'],['邪术师 6','旧日支配者能力成长；暴击相关恐惧只当额外收益，不当稳定控场。'],['邪术师 7','四环契约法术。'],['邪术师 8','魅力+2或警觉。'],['邪术师 9','五环契约法术。'],['邪术师 10','补祈唤，优先解决队伍缺少的控制或自保。'],['邪术师 11','取得六环秘法术。'],['邪术师 12','警觉、幸运或战地施法者。']],rotation:['先让魔宠侦察或占位，再把区域控制放在敌人必经处。','饥饿之寒会遮挡视线并影响双方，队友进入前先沟通路线。','控制法术位在短休恢复，打完一场再决定是否短休。'],gearPlan:{core:['spellsparkler'],strong:['weave-robe','night-walkers'],replacements:[{for:'spellsparkler',alternatives:['markoheshkir'],reason:'终盘法杖更适合高豁免 DC；失去前期命中戏法的闪电充能。'}]},risks:['召唤物会堵路、拖慢回合并可能触发战斗。','区域控制会遮挡己方视线，队友需要绕行或具备相应视野。','恐惧和控制通常有豁免，不能保证每次成立。']}),
  casterBuild({id:'wizard-evocation-blast',name:'塑能学派 · 安全范围爆发',classId:'wizard',subclass:'塑能学派',split:'塑能学派法师 12',tier:'强力',difficulty:'容易',wiki:'https://bg3.wiki/wiki/School_of_Evocation',levels:[['法师 1','法术书和奥术回收起步；抄录常用伤害与防护卷轴。'],['法师 2','选择塑能学派，塑能法术可避开友军。'],['法师 3','二环法术，准备匕首之云或其他范围工具。'],['法师 4','智力+2。'],['法师 5','三环法术，火球术或闪电束按地形选择。'],['法师 6','塑能学派能力成长，继续利用安全范围伤害清场。'],['法师 7','四环法术。'],['法师 8','智力+2或警觉。'],['法师 9','五环法术。'],['法师 10','塑能法术进一步强化；仍须检查中立单位和关键物件。'],['法师 11','六环法术。'],['法师 12','警觉、幸运或战地施法者。']],rotation:['敌人聚拢时以塑能范围法术清场，仍要避开中立 NPC 与易爆物。','火焰、闪电和力场按抗性与地形切换。','奥术回收只在短休前或关键连续战后使用。'],gearPlan:{core:['markoheshkir'],strong:['weave-robe','amulet-health'],replacements:[{for:'markoheshkir',alternatives:['spellsparkler'],reason:'进入第三章前的前期法杖；施法上限与免费法术能力较低。'}]},risks:['塑能学派保护的是友军，不会让中立 NPC、任务物件或地形免疫。','范围法术仍受元素抗性和射线遮挡影响。','高环法术位有限，清小怪时别每场都耗尽。']}),
  casterBuild({id:'wizard-divination-control',name:'预言学派 · 预兆控场',classId:'wizard',subclass:'预言学派',split:'预言学派法师 12',tier:'稳健',difficulty:'高',wiki:'https://bg3.wiki/wiki/School_of_Divination',levels:[['法师 1','法术书与奥术回收；准备护盾术和控制法术。'],['法师 2','选择预言学派，长休后获得预兆骰，可替换攻击骰或豁免骰。'],['法师 3','二环控制，准备定身术或迷惑类法术。'],['法师 4','智力+2。'],['法师 5','三环控制法术。'],['法师 6','预言学派能力成长，靠符合条件的法术恢复预兆资源。'],['法师 7','四环控制或机动。'],['法师 8','智力+2或警觉。'],['法师 9','五环控制。'],['法师 10','补足预言与防护法术书。'],['法师 11','六环法术。'],['法师 12','警觉、幸运或战地施法者。']],rotation:['看到低预兆骰时优先替换敌人的关键豁免，让控制更可能命中。','高预兆骰可保护队友关键豁免或促成自己的命中；不要浪费在无关检定。','预兆骰用完后按普通控制法师打法，保留护盾术自保。'],gearPlan:{core:['markoheshkir'],strong:['weave-robe','amulet-health'],replacements:[{for:'markoheshkir',alternatives:['spellsparkler'],reason:'第三章前可用的法杖；不会提供奥术电池。'}]},risks:['预兆骰数量有限且长休刷新，不是每回合都能改骰。','控制目标仍需满足法术规则，例如免疫状态或视线限制。','预言玩法需要读战场与反应窗口，操作负担较高。']}),
  casterBuild({id:'wizard-bladesinging',name:'剑舞法师 · 机动施法近战',classId:'wizard',subclass:'剑舞法师',split:'剑舞法师法师 12',tier:'稳健',difficulty:'高',wiki:'https://bg3.wiki/wiki/Bladesinging',levels:[['法师 1','法术书起步；用敏捷武器和护盾术度过前期。'],['法师 2','选择剑舞法师，剑舞状态提高机动与防御；穿中／重甲或持盾会限制剑舞。'],['法师 3','二环法术，准备迷踪步与防护。'],['法师 4','智力+2或敏捷+2，先补足命中与法术难度的短板。'],['法师 5','三环法术；近战危险时仍可用远程法术。'],['法师 6','剑舞法师获得额外攻击，正常时进行两次武器攻击；只有 Booming Blade（雷鸣剑）的特殊互动可替代其中一次攻击。'],['法师 7','四环法术。'],['法师 8','智力或敏捷+2。'],['法师 9','五环法术。'],['法师 10','剑舞法师能力成长，保持专注与站位优先于贪刀。'],['法师 11','六环法术。'],['法师 12','警觉、战地施法者或属性提升。']],rotation:['剑舞开启后切入边缘目标，以两次普通武器攻击为默认回合；满足特殊互动时才用 Booming Blade（雷鸣剑）替代其中一次。','被多名敌人包围时用迷踪步或控制撤离，不把高防御当作坦克无敌。','需要维持专注时优先留反应给护盾术，并让队友协助封锁敌人。'],gearPlan:{core:['undermountain'],strong:['weave-robe','night-walkers'],replacements:[{for:'undermountain',alternatives:['phalar'],reason:'暂未取得短剑时可用双手剑提供团队工具；会失去灵巧武器与暴击骰收益。'}]},risks:['剑舞法师是 Patch 8 新子职业；它是机动副前排，不是重甲盾牌坦克。','剑舞、近战站位和专注会同时消耗注意力。','近战武器攻击与施法属性可能不同，升级时要明确主轴。']})
);
Object.assign(BUILD_LIBRARY.find(function(build){return build.id==='monk-open-hand-thief';}),{
  sources:[PATCH8_SOURCE,'https://bg3.wiki/wiki/Way_of_the_Open_Hand'],
  gearPlan:{core:['soul-catching'],strong:['vest-soul'],replacements:[{for:'soul-catching',alternatives:['dex-gloves'],reason:'希望之邸前的属性过渡；不提供徒手终盘附伤。'}]},
  originHints:[{origin:'邪念',note:'默认推荐；不改变职业选择自由'}]
});
var equipmentPlans={
  'barbarian-giant-throw':{core:['pike','flinging','nyrulna'],strong:['gloves','cloth'],replacements:[{for:'nyrulna',alternatives:['pike'],reason:'阿卡比路线前继续使用回旋长矛；少了终盘雷鸣爆炸，但不会误伤贴身队友。'}]},
  'barbarian-berserker-throw':{core:['pike','flinging','nyrulna'],strong:['gloves','cloth'],replacements:[{for:'nyrulna',alternatives:['pike'],reason:'终盘三叉戟前保留回旋长矛；少了范围雷鸣，但投掷回归更容易控场。'}]},
  'barbarian-wildheart-melee':{core:['giantslayer'],strong:['cloth','phalar'],replacements:[{for:'giantslayer',alternatives:['phalar'],reason:'安苏路线前可用团队长剑过渡；失去高力量双手武器的终盘爆发。'}]},
  'bard-swords-archer-control':{core:['arcane-acuity','mystic-scoundrel'],strong:['titanstring','gontr'],replacements:[{for:'gontr',alternatives:['titanstring'],reason:'钢铁卫士路线前，以力量弓维持远程命中后的控场循环；失去贡德信赖的团队防护。'}]},
  'bard-swords-melee':{core:['undermountain'],strong:['phalar','arcane-acuity'],replacements:[{for:'undermountain',alternatives:['phalar'],reason:'短剑尚未取得时以双手团队长剑过渡；不再是灵巧副手与暴击骰路线。'}]},
  'bard-glamour-support':{core:['whispering-promise'],strong:['aid-comfort','hellrider-pride'],replacements:[{for:'whispering-promise',alternatives:['ring-salving'],reason:'无法从沃罗取得戒指时，改用同为戒指栏位的疗愈之戒保留法术位治疗增益；会失去治疗触发的祝福。'}]},
  'cleric-light-orb':{core:['luminous'],strong:['belligerent','callous','stormy'],replacements:[{for:'luminous',alternatives:['yuan-ti'],reason:'没有发光护甲时，以同为护甲栏位的元提鳞甲维持防御；失去光耀法球主轴。'}]},
  'cleric-tempest-wet':{core:['markoheshkir'],strong:['belligerent','stormy','spellcrux'],replacements:[{for:'markoheshkir',alternatives:['blood-lathander'],reason:'第三章前以钉头锤过渡；失去法术 DC、命中与奥术电池。'}]},
  'cleric-life-support':{core:['whispering-promise','hellrider-pride'],strong:['aid-comfort','spellcrux'],replacements:[{for:'hellrider-pride',alternatives:['reviving-hands'],reason:'林地奖励错过时，第三章可用同为手套栏位的复苏之手继续以治疗提供刃甲；取得时间更晚。'}]},
  'druid-stars-caster':{core:['spellcrux'],strong:['markoheshkir','amulet-health'],replacements:[{for:'markoheshkir',alternatives:['spellsparkler'],reason:'第三章法杖前使用任务奖励法杖；失去法术 DC 与奥术电池。'}]},
  'druid-moon-wildshape':{core:['moonbasking'],strong:['shapeshifter-boon','amulet-health'],replacements:[{for:'moonbasking',alternatives:['cloth'],reason:'第三章前，人形形态可使用同为服装栏位的优雅布衣；野性变形时不会获得沐月长袍的承伤收益。',fallback:{mode:'human-form',gear:['cloth','shapeshifter-boon','amulet-health'],reason:'图鉴没有第二件可替代沐月长袍野性变形效果的服装；在取得前明确改用人形施法／侦察配装，而非把人形衣物误称为野性变形替代品。'}}]},
  'druid-land-control':{core:['spellcrux'],strong:['hood-weave','markoheshkir'],replacements:[{for:'hood-weave',alternatives:['arcane-acuity'],reason:'头部毕业件与其他主控竞争时，改用同为头盔栏位的奥术敏锐头盔；需先以武器命中叠层，不能当作无条件 DC 加成。'}]},
  'fighter-battlemaster-archer':{core:['gontr'],strong:['titanstring','darkfire'],replacements:[{for:'gontr',alternatives:['titanstring'],reason:'铸造厂路线前可用力量弓过渡；失去贡德信赖的命中支援与防护。'}]},
  'fighter-arcane-archer':{core:['titanstring'],strong:['arcane-acuity','dead-shot'],replacements:[{for:'titanstring',alternatives:['dead-shot'],reason:'没有可靠力量加成时改用终盘商店弓；失去力量转伤，但保留命中与暴击收益。'}]},
  'monk-shadow-infiltrator':{core:['cunning-brume'],strong:['night-walkers','undermountain'],replacements:[{for:'cunning-brume',alternatives:['cloak-protection'],reason:'马蒂斯路线不可用时用同为斗篷栏位的防护斗篷补 AC 与豁免；失去脱离后的遮蔽与重新潜行工具。'}]},
  'monk-drunken-master':{core:['punch-drunk'],strong:['night-walkers','cloth'],replacements:[{for:'punch-drunk',alternatives:['undermountain'],reason:'无法维持醉酒或酒馆首领路线未完成时，用灵巧短剑过渡；失去醉酒时的雷鸣主题收益。'}]},
  'sorcerer-shadow-control':{core:['hood-weave'],strong:['weave-robe','spellcrux'],replacements:[{for:'hood-weave',alternatives:['arcane-acuity'],reason:'头部毕业件给其他主控时，改用同为头盔栏位的奥术敏锐头盔；需先以武器命中叠层，不能把它当作无条件 DC 加成。'}]},
  'warlock-control-summon':{core:['hood-weave'],strong:['spellcrux','weave-robe'],replacements:[{for:'hood-weave',alternatives:['arcane-acuity'],reason:'头部装备被队友占用时，改用同为头盔栏位的奥术敏锐头盔；需先以武器命中叠层，再投入关键控制。'}]},
  'wizard-divination-control':{core:['hood-weave','markoheshkir'],strong:['weave-robe','spellcrux'],replacements:[{for:'hood-weave',alternatives:['arcane-acuity'],reason:'帽子让给另一位主控时，改用同为头盔栏位的奥术敏锐头盔；需先以武器命中叠层，失去编织之帽的直接法术攻击与 DC 加值。'}]}
};
Object.keys(equipmentPlans).forEach(function(id){var build=BUILD_LIBRARY.find(function(entry){return entry.id===id;});if(build)build.gearPlan=equipmentPlans[id];});
Object.assign(BUILD_LIBRARY.find(function(build){return build.id==='barbarian-giant-throw';}),{risks:['投掷轨迹会被横梁、门框和高低差阻挡。','尼鲁纳的雷鸣爆炸会波及近战队友，贴脸时改用回旋长矛。','狂暴期间不能施法或维持专注。']});
Object.assign(BUILD_LIBRARY.find(function(build){return build.id==='barbarian-berserker-throw';}),{risks:['狂乱投掷和巨人之道的元素投掷是不同机制。','尼鲁纳的范围雷鸣不适合队友贴身的目标；可换回回旋长矛。','狂暴限制施法和专注。']});
globalThis.BUILD_LIBRARY=BUILD_LIBRARY;
